// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class TornarItensObrigatorios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TornarItensObrigatorios));
        
        string IMigrationMetadata.Id
        {
            get { return "201711282316083_TornarItensObrigatorios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
